prebuilt_cxx_library(
  name = 'cds_test',
  header_only = True,
  header_namespace = 'cds_test',
  exported_headers = subdir_glob([
    ('include/cds_test', '**/*.h'),
  ]),
  visibility = [
    '//test/...',
  ],
)
